backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/markdown-wiki
  branch: main
  commit_author:
    name: "Wiki Bot"
    email: "wiki-bot@users.noreply.github.com"
  base_url: https://your-auth-proxy.example.com
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "wiki"
    label: "Wiki Pages"
    folder: "docs"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
